Makejump прыжок
csit-sgu/mit-game-2024_1 pull request #25
Opened 2024-04-27 08:20 UTC by NomenConservandum

Implemented MakeJump function. The number 30 gives a player an ability to jump as high as 2.5 blocks. It might be changed in the future if there will be a need to.

2024-04-27 09:32 UTC, vasthecat requested changes

2024-04-27 09:32 UTC, vasthecat commented on user.cpp
> +		can_jump = false;
This won't compile.

2024-04-27 17:52 UTC, closed without merging

2024-04-27 18:10 UTC, vasthecat commented
Why did you close the PR?

2024-04-28 15:45 UTC, NomenConservandum commented
> Why did you close the PR?

Needed some testing and decided to close this one and open another when it is done. Now it's ready and I opened a separate pull-request. Was it better to continue with this one?