Solve collision
csit-sgu/mit-game-2024_1 pull request #27
Opened 2024-04-27 15:08 UTC by Anarchy73

Добавлена функция SolveCollision.

2024-05-12 07:02 UTC, nrydanov requested changes

2024-05-12 07:02 UTC, nrydanov commented on user.cpp
> +    else obj.position.x -= c.overlap.x *1.01;
You've missed some spaces here.

2024-05-12 07:02 UTC, nrydanov commented on user.cpp
> +
Remove this change, please.

2024-05-12 07:02 UTC, nrydanov commented on user.cpp
> +
And those too.

2024-05-12 11:34 UTC, nrydanov approved these changes

2024-05-13 18:12 UTC, mchernigin submitted a review, later dismissed
Мне очень больно смотреть на это форматирование. Не нужно писать в одной строке и условие, и выражение. Но я терплю.

2024-05-14 08:32 UTC, vasthecat requested changes

2024-05-14 08:32 UTC, vasthecat commented on user.cpp
> +    if (abs(c.overlap.y) < abs(c.overlap.x)) obj.position.y -= c.overlap.y * 1.01;
Этот коэффициент лишний. Решить коллизию он не помогает, но при этом нахождение коллизий с врагами начинает работать хуже.

2024-05-19 14:30 UTC, vasthecat approved these changes
LGTM

2024-05-19 15:37 UTC, nrydanov approved these changes

2024-05-19 16:00 UTC, merged