Added CheckCollision func
csit-sgu/mit-game-2024_1 pull request #29
Opened 2024-04-29 07:45 UTC by ProstoLive

2024-04-29 10:47 UTC, mchernigin commented
Something terrifying hapend here... There are 2 problems.

1. You've changed file encoding of new line encoding of every file in the project, so your pull request proposes changes in 45 files. Which it shouldn't. It should only change one function — `CheckCollision`.

2. There actually were less than 45 files in the project. You actually committed build artefacts as well. Which is not a good thing. Git repositories should not contain results of compilation as it is a) platform specific and will not work on my machine b) can be reproduced just by running CMake.

So, before we can review this, you would need to fix those 2 things. Only then, I could take a look at your CheckCollision implementation.

2024-05-12 06:55 UTC, nrydanov approved these changes

2024-05-12 06:55 UTC, nrydanov commented on user.cpp
> +    Vector2 d = { abs(obj1.position.x - obj2.position.x), abs(obj1.position.y - obj2.position.y) };
You could use overrided minus operator for vectors and just write `obj1.position - obj2.position` and then take abs where it's needed, but in general everything is ok.

2024-05-13 18:10 UTC, mchernigin requested changes

2024-05-13 18:10 UTC, mchernigin commented on user.cpp
> +    {
Здесь не хватает поправок в вектор `q`: если `d.x` отрицателен, то значение `q.x` должно быть также отрицательным. Аналогично со второй координатой.

Иначе у тебя персонаж ходит сквозь стены)

P.S.: не подразумевается, что ты будешь в d хранить уже **модуль** разницы позиций.

2024-05-14 08:56 UTC, vasthecat commented on user.cpp
> +    {
Это одно из заданий, в котором неправильно описана реализация функции. Она должна вычислять какое пересечение у объектов относительно центров друг друга, а не краёв (поэтому используются полусуммы). С помощью знаков компонент вектора q кодируется то, с какой стороны произошло столкновение. Если объект 1 был правее объекта 2, то коллизия будет отрицательной по x.

2024-05-14 18:23 UTC, ProstoLive commented on user.cpp
> +    {
> Это одно из заданий, в котором неправильно описана реализация функции. Она должна вычислять какое пересечение у объектов относительно центров друг друга, а не краёв (поэтому используются полусуммы). С помощью знаков компонент вектора q кодируется то, с какой стороны произошло столкновение. Если объект 1 был правее объекта 2, то коллизия будет отрицательной по x.

Так полусуммы и нужны для определения пересечения относительно краёв. Если бы мы вычисляли пересечение от центров, то достаточно было бы вычислить разницу между obj1.position и obj2.position, которые задаются центрами объектов.

Вычитая из вектора d (разницы координат центров объектов) полусуммы по обоим координатам мы приходим к разнице в координатах относительно краёв объектов, разве нет?

2024-05-14 19:01 UTC, ProstoLive commented on user.cpp
> +    {
> Здесь не хватает поправок в вектор `q`: если `d.x` отрицателен, то значение `q.x` должно быть также отрицательным. Аналогично со второй координатой.

Не соглашусь, знак координаты в векторе d зависит от того, из координаты какого объекта мы будем вычитать координаты другого, а знак в векторе q - от того, пересекаются ли коллайдеры.

В случае, когда объект №1 находится левее объекта №2 по оси, и вычитаем мы из координат объекта №1 координаты объекта №2, координаты вектора d будут отрицательны. При этом объекты могут не пересекаться и координаты вектора q будут положительны.

Вообще, в условиях задачи координаты вектора d являются расстоянием между проекциями центров объектов на оси Х и Y, из-за чего знаком вектора d можно пренебречь, так как расстояние - величина строго положительная и берётся по модулю.

2024-05-19 15:13 UTC, vasthecat commented on user.cpp
> +    {
Знаки в промежуточных векторах d и q действительно имеют такой смысл, но итоговом векторе с помощью абсолютных значений кодируется непосредственно пересечение (площадь), а с помощью знаков кодируется направление пересечения.

Твой результат применяется в функции `FixCollisions`, где для реализации предполагаются коллизии со знаком, которым кодируется сторона, с которой произошла коллизия. Эти две функции, конечно, можно реализовать без коллизии со знаком, но тогда этот знак всё равно придётся вычислить именно тем способом, который мы предлагаем (скопировать знаки компонент d на компоненты итогового вектора).

Да, можно разделить этот вектор на два - вектор направления между двумя пересекающимися объектами и саму коллизию. Мы в своём решении предлагаем их просто объединить в один, именно потому что один из векторов фактически содержит только знаки компонент, а другой содержит строго положительные значения пересечения.

> // Если коллизия не произошла (c.exists равно false), то ничего делать не нужно.
// Если коллизия по горизонтали (std::abs(c.overlap.x)) больше, чем по
// вертикали (std::abs(c.overlap.y)), то объект obj перемещается на величину
// c.overlap.x влево или вправо в зависимости от направления коллизии. В
// противном случае, объект перемещается на величину c.overlap.y вверх или вниз
// в зависимости от направления коллизии.

2024-05-26 09:31 UTC, vasthecat approved these changes
LGTM

2024-05-28 15:53 UTC, nrydanov approved these changes
Noice

2024-06-01 05:15 UTC, mchernigin approved these changes

2024-06-01 18:47 UTC, merged