Added function ApplyGravity
csit-sgu/mit-game-2024_1 pull request #31
Opened 2024-04-29 18:31 UTC by aragami3070

Добавлена функция ApplyGravity

2024-05-12 06:48 UTC, nrydanov requested changes

2024-05-12 06:48 UTC, nrydanov commented on user.cpp
> +    if(obj.physics.enabled == true && obj.collider.of_type(dynamic) == true)
Please, add spaces between if and if-body.

2024-05-12 06:48 UTC, nrydanov commented on user.cpp
> +        obj.physics.acceleration.y = GRAVITY;
You don't add gravity, you make it equal to it. Also, it's incorrect in terms of physics. Also, as far as I remember, Y axis is directed on top, so you have wrong sign here.

2024-05-12 06:48 UTC, nrydanov commented on user.cpp
> +    if(obj.physics.enabled == true && obj.collider.of_type(dynamic) == true)
Also, `obj.coilleder.of_type(dynamic)` is already a boolean value, so you don't need to comparise it with `true` directly.

2024-05-14 08:38 UTC, vasthecat reviewed
You should link corresponding issue, so that it may be closed automatically.

2024-05-19 15:22 UTC, aragami3070 commented
Внес правки, но правки на гравитацию не делал, так как тестил с Артемом с другими функциями и данный вариант работает нормально(13.05 на паре показали).

2024-05-19 15:27 UTC, vasthecat commented on user.cpp
> +        obj.physics.acceleration.y = GRAVITY;
Technically, this would work in case of this game, since only this function uses acceleration and it is *subtracted* in code lower. But physically acceleration should be *added*, so sign of gravity should be negative. And yes, you should *subtract* gravity from Oy of acceleration, not set to this value. In case of this particular game, this also would work *technically*, since only gravity affects Oy of acceleration, but this is not true in general case.

2024-05-19 15:30 UTC, vasthecat submitted a review, later dismissed
Технически, это будет работать в данном конкректном случае этой игры, но знаки неверны с физической точки зрения в общем случае. Поставлю апрув, но насколько это корректно решат Никита или Миша.

2024-05-26 09:32 UTC, vasthecat approved these changes
LGTM

2024-05-28 15:52 UTC, nrydanov approved these changes

2024-05-29 13:12 UTC, merged