Добавлена функция проверка смерти игрока
csit-sgu/mit-game-2024_1 pull request #32
Opened 2024-05-13 16:11 UTC by quexzz

2024-05-13 16:23 UTC, nrydanov approved these changes
Отлично!

2024-05-13 17:29 UTC, mchernigin approved these changes
Похоже на правду

2024-05-14 08:41 UTC, vasthecat requested changes
Свяжи с этим PR соответствующую issue, чтобы она могла автоматически закрыться при мердже.

2024-05-19 14:33 UTC, vasthecat approved these changes
LGTM

2024-06-01 05:23 UTC, nrydanov commented
Нужно смерджить PR, чтобы задание было засчитано.

2024-06-01 06:15 UTC, merged