Реализовал функцию ApplyOnDeath, добавил звуки смерти
csit-sgu/mit-game-2024_1 pull request #33
Opened 2024-05-13 16:14 UTC by ArtemFilin9

2024-05-13 16:24 UTC, nrydanov approved these changes
Отлично!

2024-05-13 17:27 UTC, mchernigin submitted a review, later dismissed
Выглядит правдоподобно!

2024-05-14 08:36 UTC, vasthecat requested changes

2024-05-14 08:36 UTC, vasthecat commented on user.cpp
> +void ApplyOnDeath(Context& ctx, Object& obj)
Не нужно изменять строки, которые не относятся к выполнению задания. Форматирование стоит изменять только если это и есть цель коммита. Иначе можно испортить git blame

2024-05-14 08:40 UTC, vasthecat reviewed
И свяжи с этим PR соответствующую issue, чтобы она могла автоматически закрыться при мердже.

2024-05-14 09:47 UTC, ArtemFilin9 commented
Связал PR с соответствующим issue

2024-05-19 11:43 UTC, nrydanov approved these changes

2024-05-19 14:31 UTC, vasthecat approved these changes
LGTM

2024-05-22 09:46 UTC, merged