Realised UpdateBullet function
csit-sgu/mit-game-2024_1 pull request #37
Opened 2024-05-27 12:35 UTC by haritonn

2024-05-28 15:53 UTC, vasthecat requested changes

2024-05-28 15:53 UTC, vasthecat commented on user.cpp
> +    obj.position += obj.bullet.speed;
Speed should be multiplied by `dt`, so that it doesn't depend on FPS of application.

2024-05-28 18:24 UTC, haritonn commented
I actually have no idea why I merged the remote branch with the local, it was like testing idk :/

2024-06-01 05:25 UTC, mchernigin approved these changes
Кажется, всё работает корректно

2024-06-01 05:27 UTC, vasthecat approved these changes
LGTM

2024-06-02 12:47 UTC, merged